version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ees-python"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1impwnxeg5k2j"
s3_prefix = "ees-python"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
