AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Elastic Event Store

Globals:
  Function:
    Timeout: 60

Parameters:
  Environment:
    Description: Environment Name
    Type: String
    Default: dev
  InstanceName:
    Description: Instance Name
    Type: String
    Default: eventstore
  ReadCapacityUnits:
    Description: Provisioned read throughput
    Type: Number
    Default: '1'
    MinValue: '1'
    MaxValue: '10000'
    ConstraintDescription: must be between 1 and 10000
  WriteCapacityUnits:
    Description: Provisioned write throughput
    Type: Number
    Default: '1'
    MinValue: '1'
    MaxValue: '10000'
    ConstraintDescription: must be between 1 and 10000

Resources:
  EventStoreTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Join [ '_', ['ees', 'db', !Ref Environment, !Ref InstanceName] ]
      AttributeDefinitions:
      - AttributeName: stream_id
        AttributeType: S
      - AttributeName: changeset_id
        AttributeType: N
      - AttributeName: global_enum_page
        AttributeType: N
      - AttributeName: global_enum_item
        AttributeType: N
      - AttributeName: first_event
        AttributeType: N
      - AttributeName: last_event
        AttributeType: N
      KeySchema:
      - AttributeName: stream_id
        KeyType: HASH
      - AttributeName: changeset_id
        KeyType: RANGE
      LocalSecondaryIndexes:
      - IndexName: FirstEventNumber
        KeySchema:
        - AttributeName: stream_id
          KeyType: HASH
        - AttributeName: first_event
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
      - IndexName: LastEventNumber
        KeySchema:
        - AttributeName: stream_id
          KeyType: HASH
        - AttributeName: last_event
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
      GlobalSecondaryIndexes:
      - IndexName: EmumerationIndex
        KeySchema:
        - AttributeName: global_enum_page
          KeyType: HASH
        - AttributeName: global_enum_item
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: !Ref ReadCapacityUnits
          WriteCapacityUnits: !Ref WriteCapacityUnits
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref ReadCapacityUnits
        WriteCapacityUnits: !Ref WriteCapacityUnits
      StreamSpecification:
        StreamViewType: NEW_IMAGE
  CommandsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ees/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        Version:
          Type: Api
          Properties:
            Path: /version
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/version/"
  CommandsFunction:
    Description: "Commands Lambda Function ARN"
    Value: !GetAtt CommandsFunction.Arn
  CommandsFunctionIamRole:
    Description: "Implicit IAM Role created for the commands function"
    Value: !GetAtt CommandsFunctionRole.Arn
